version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-messagesdb}
      MYSQL_USER: ${MYSQL_USER:-appuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-apppass}
    volumes:
      - db_data:/var/lib/mysql
      - ./create_table.sql:/docker-entrypoint-initdb.d/create_table.sql:ro
    ports:
      - "3306:3306"
  app:
    build: .
    environment:
      DB_HOST: db
      DB_USER: ${MYSQL_USER:-appuser}
      DB_PASSWORD: ${MYSQL_PASSWORD:-apppass}
      DB_NAME: ${MYSQL_DATABASE:-messagesdb}
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db_data:
