name: Terraform CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'infra/terraform/**'
  pull_request:
    branches: [main]
    paths:
      - 'infra/terraform/**'
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - name: Terraform Init
        run: terraform -chdir=infra/terraform init
      - name: Terraform Validate
        run: terraform -chdir=infra/terraform validate
      - name: Terraform Plan
        run: terraform -chdir=infra/terraform plan
      - name: Terraform Apply (if approved)
        if: github.event_name == 'push'
        run: terraform -chdir=infra/terraform apply -auto-approve
