name: Terraform CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'infra/terraform/**'
  pull_request:
    branches: [main]
    paths:
      - 'infra/terraform/**'
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - name: Verify required secrets
        run: |
          if [ -z "${TF_VAR_db_password}" ]; then
            echo "ERROR: GitHub secret DB_PASSWORD is not set for this repository or environment." >&2
            exit 1
          fi
      - name: Terraform Init
        working-directory: infra/terraform/environments/production
        run: terraform init
      - name: Terraform Validate
        working-directory: infra/terraform/environments/production
        run: terraform validate
      - name: Terraform Plan
        timeout-minutes: 10
        working-directory: infra/terraform/environments/production
        run: terraform plan
      - name: Terraform Apply (if approved)
        if: github.event_name == 'push'
        working-directory: infra/terraform/environments/production
        run: terraform apply -auto-approve
