name: Terraform CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'infra/terraform/**'
  pull_request:
    branches: [main]
    paths:
      - 'infra/terraform/**'
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - name: Terraform Init
        working-directory: infra/terraform/environments/production
        run: terraform init
      - name: Terraform Validate
        working-directory: infra/terraform/environments/production
        run: terraform validate
      - name: Terraform Plan
        working_directory: infra/terraform/environments/production
        run: terraform plan
      - name: Terraform Apply (if approved)
        if: github.event_name == 'push'
        working_directory: infra/terraform/environments/production
        run: terraform apply -auto-approve
